### PR TITLE
[chunithm] allow timer patches to go negative

### PR DESCRIPTION
**Pull request by beer-psi**
Interestingly, it turns out that if the timers go negative, the resulting in-game timer is this value subtracted from 968 (e.g. if the timer is -1, then the in-game value is 967).

Needs help on the wording in the tooltip, since `968 - timer` is technically wrong.

### CODE REVIEW

**Comment by akitakedits** [comment]
If set to negative, the resulting timer will be 968 - value

Maybe?

**Comment by beer-psi** [comment]
> If set to negative, the resulting timer will be 968 - value
> 
> Maybe?

It's technically wrong because `968 - value` would be `968 - (-1) = 968 + 1`. That's the main problem I'm having with the tooltip.

**Comment by akitakedits** [comment]
If set to negative, the timer becomes 968 + value

Then? Sure it's intuitive maybe, but it essentially adds the negative value to 968, same as subtracting the absolute of the value.

**Comment by beer-psi** [comment]
Sure, that probably works. Also added an example to clarify things.

**Pull request merged**
