### PR TITLE
feat: amdaemon patcher

### PR DESCRIPTION
**Pull request by beer-psi**
motivation: there are useful patches for amdaemon for home play, but the game itself doesn't need/can't have a patcher (for example, Unity games). this provides an easy and centralized location for patching amdaemon.

suggestions on what the icon should be are welcome.

### CODE REVIEW

**Comment by akitakedits** [comment]
can you provide a specific example where this is of any use?

**Comment by beer-psi** [comment]
patching amdaemon on unity games comes to mind

**Comment by akitakedits** [comment]
like?

**Comment by beer-psi** [comment]
infinite credits, using a localhost server, there's only like 3 patches for each amdaemon version.

**Comment by akitakedits** [comment]
I can read, I read the files you changed.
I just don't understand what the purpose is. If people need patches for a specific game, they can go to that game's page.
Providing generic amddaemon patches doesn't make much sense to me.

**Comment by beer-psi** [comment]
There are no pages for any Unity games, since the main game isn't patched with hex edits. Moreover, amdaemon builds aren't exclusive to each game.

**Comment by akitakedits** [comment]
would it then make more sense to move every game's amddaemon to that page instead of having duplicates and needing to maintain two different patchers for amddaemon's?

**Comment by beer-psi** [comment]
you're going to have to duplicate patchers *anyways*, since multiple different game versions may use the same amdaemon build. for example:
- CHUNITHM NEW through SUN+ used `026fb4a0`
- Every Unity game uses build `46d47eab`, because the `amdaemon_api.dll` stub is only dumped for that version.

**Comment by akitakedits** [comment]
Alright then I'm over it, merging

**Pull request merged**
